// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RRInventory.Data;
using RRInventory.Models;
using System;

namespace RRInventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RRInventory.Models.Account", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<DateTime>("SubscriptionEndDate");

                    b.Property<string>("Zipcode");

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("RRInventory.Models.Image", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Jpg");

                    b.Property<string>("Thumbnail");

                    b.HasKey("ID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("RRInventory.Models.Item", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountID");

                    b.Property<string>("Description");

                    b.Property<Guid>("ImageID");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("ModelNumber");

                    b.Property<string>("Railroad");

                    b.Property<int>("Type");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ImageID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("RRInventory.Models.Item", b =>
                {
                    b.HasOne("RRInventory.Models.Account", "Account")
                        .WithMany("Items")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RRInventory.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
